theme: jekyll-theme-minimal
title: Tsung-Yiou Hsieh
description: PhD in Marketing
logo: https://media.licdn.com/dms/image/D5603AQGbdnj7JWk_qA/profile-displayphoto-shrink_800_800/0/1717211929383?e=1723680000&v=beta&t=m2vchY_WwDEBeCaM8moCUetLP91HR4hInJWd3pp7uvE
show_downloads: false
google_analytics: G-FHE55JD0YL
